# Site settings
title: Jin Park - Human
description: Jin Park
author: Jin Park
email: jin+blog@jinpark.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jinpark.net" # the base hostname & protocol for your site
github_username:  jinpark

# Build settings
include: [_pages]
markdown: kramdown
permalink: /blog/:year/:month/:title
sass:
    style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist